config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]


end

app/models/user.rb
# (с) goodprogrammer.ru
#
# Модель пользователя
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # юзер может создавать много событий
  has_many :events
  has_many :comments
  has_many :subscriptions
  # имя юзера должно быть, и не длиннее 35 букв
  validates :name, presence: true, length: {maximum: 35}

  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  private

  def set_name
    self.name = "Товарисч №#{rand(777)}" if self.name.blank?
  end

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email).update_all(user_id: self.id)
  end
end

app/controllers/users_controller.rb
# (с) goodprogrammer.ru
#
# Контроллер, управляющий событиями
class UsersController < ApplicationController
  # встроенный в девайз фильтр - посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show]

  # задаем объект @user для шаблонов и экшенов
  before_action :set_current_user, except: [:show]

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>

    <%= render partial: 'partials/form_errors', locals: {model: @user} %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :avatar %>
      <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
      <%= f.file_field :avatar %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon') %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row">
  <div class="col-md-6 buffer-top">

    <%= render 'form' %>

    <p class="buffer-top">
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user) %>

  <% if @user == current_user %>
    <p class="buffer-top">
      <%= link_to "Редактировать профиль", edit_user_path(@user), class: 'btn btn-default' %>
    </p>
  <% end %>
</div>
<%# Выводим список событий, организованных пользователем %>
<div class="row">
  <div class="col-md-12">
    <% if @user.events.any? %>
      <h3>Организовал:</h3>
      <div class="row">
        <%= render partial: 'events/event', collection: @user.events %>
      </div>
    <% else %>
      <p class="buffer-top">Пользователь пока не организовал ни одного события</p>
    <% end %>
  </div>
</div>